set(source_list ${source_list}${PROJ_PATH}/Application/Src/main.c
${PROJ_PATH}/Core/Src/syscalls.c
${PROJ_PATH}/Core/Src/sysmem.c
${PROJ_PATH}/Core/Src/UART.c
${PROJ_PATH}/Core/startup_stm32f429zitx.s
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmpi2c.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_tim_template.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_i2c.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smbus.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/Legacy/stm32f4xx_hal_eth.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/Legacy/stm32f4xx_hal_can.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rtc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_spi.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma2d.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_tim.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_rtc_alarm_template.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_crc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rng.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_msp_template.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_rtc_wakeup_template.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dac.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_lptim.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_pwr.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dfsdm.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus.c
${PROJ_PATH}/Drivers/CMSIS/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
${PROJ_PATH}/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c
)
